# Generated by Django 5.2.4 on 2025-08-01 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_attendanceprediction_high_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceprediction',
            name='high_temp',
        ),
        migrations.RemoveField(
            model_name='attendanceprediction',
            name='precipitation',
        ),
        migrations.CreateModel(
            name='SevenDayPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('high_temp', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.location')),
            ],
        ),
    ]
