# Generated by Django 5.2.4 on 2025-08-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_attendanceprediction_high_temp_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(fields=('date', 'location'), name='unique_date_location'),
        ),
    ]
